### ISSUE TITLE
Mod causing crashes

### ISSUE THREAD

**Issue by InsaneBuildEnvironment** [george-jones/csm-exportelectricity#2]
It seems like this mod is causing the game to crash. Not sure what circumstances cause the crash, but here's the stack trace from the first time it happened:

```
00007FF7AD0765D6 (Cities) Scripting::ScriptingWrapperFor
0000000005BE345C (Mono JIT Code) (wrapper managed-to-native) UnityEngine.Object:FindObjectsOfType (System.Type)
0000000068A8E119 (Mono JIT Code) UnityEngine.Object:FindObjectsOfType<object> ()
0000000149C1ADF5 (Mono JIT Code) ExportElectricityMod.EconomyExtension:OnUpdateMoneyAmount (long)
0000000149C1AD3B (Mono JIT Code) EconomyWrapper:OnUpdateMoneyAmount (long)
0000000016469D5D (Mono JIT Code) EconomyManager:SimulationStepImpl (int)
000000001643B06D (Mono JIT Code) SimulationManagerBase`2<object, object>:SimulationStep (int)
00000000164692F5 (Mono JIT Code) EconomyManager:ISimulationManager.SimulationStep (int)
0000000016250B54 (Mono JIT Code) SimulationManager:SimulationStep ()
0000000016230FBB (Mono JIT Code) SimulationManager:SimulationThread ()
0000000005BA8BBB (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
00007FFAD73E4043 (mono) mono_set_defaults
00007FFAD73383AD (mono) mono_runtime_invoke
00007FFAD7361743 (mono) mono_thread_interruption_request_flag
00007FFAD7416889 (mono) unity_mono_method_is_generic
00007FFAFF528102 (KERNEL32) BaseThreadInitThunk
00007FFAFF78C5B4 (ntdll) RtlUserThreadStart
```

And the second time:

```
00007FF60F9665D6 (Cities) Scripting::ScriptingWrapperFor
00000000058B345C (Mono JIT Code) (wrapper managed-to-native) UnityEngine.Object:FindObjectsOfType (System.Type)
0000000015E2C379 (Mono JIT Code) UnityEngine.Object:FindObjectsOfType<object> ()
00000001AC654023 (Mono JIT Code) ExportElectricityMod.EconomyExtension:OnUpdateMoneyAmount (long)
00000001AC653CDB (Mono JIT Code) EconomyWrapper:OnUpdateMoneyAmount (long)
0000000146DBC08D (Mono JIT Code) EconomyManager:SimulationStepImpl (int)
00000001BBC0DB5D (Mono JIT Code) SimulationManagerBase`2<object, object>:SimulationStep (int)
0000000146DBAF85 (Mono JIT Code) EconomyManager:ISimulationManager.SimulationStep (int)
0000000015DE3334 (Mono JIT Code) SimulationManager:SimulationStep ()
0000000015DC379B (Mono JIT Code) SimulationManager:SimulationThread ()
0000000005878BBB (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
00007FFAD7274043 (mono) mono_set_defaults
00007FFAD71C83AD (mono) mono_runtime_invoke
00007FFAD71F1743 (mono) mono_thread_interruption_request_flag
00007FFAD72A6889 (mono) unity_mono_method_is_generic
00007FFAFF528102 (KERNEL32) BaseThreadInitThunk
00007FFAFF78C5B4 (ntdll) RtlUserThreadStart
```

**Comment by george-jones** [comment]
Are you using any other mods that might be doing actions whenever money gets updated?  Or any other mods at all?  If so, and we can get it so I can reproduce the problem on my end, then maybe I can make a workaround.

**Comment by InsaneBuildEnvironment** [comment]
I'm using a ton of other mods (mostly transportation related), but none I
can think of that would affect that.

**Comment by george-jones** [comment]
If you could disable all of them and then enable one at a time, I think we could figure out which ones don't work, and even if we can't make them play nice together, at a minimum I could mention on the workshop page that this is the case.

**Comment by DinkyToyz** [comment]
I haven't tried using this mod yet myself, but since the crash happens in UnityEngine.Object:FindObjectsOfType, and you use that for getting managers, it might be worth it to get the managers another way:

The normal way of getting a manager instance is this way:
DistrictManager districtManager = Singleton<DistrictManager>.instance
EconomyManager economyManager = Singleton<EconomyManager>.instance;

I'd also suggest using try-catch blocks to catch and log exceptions in the mod, and setting a flag either at the first exception or after a certain number of exceptions in order to skip doing anything if the mod breaks. That way you can get better exception info, and avoid hindering the game too much. (You can use DebugOutputPanel.AddMessage and UnityEngine.Debug.Log for logging errors).

**Comment by Knighth** [comment]
Ditto everything DinkyToyz said.

Sample changes that avoid the findobjectsoftype method, which not the best or most efficient and safe way to access the DistrictManager or EconomyManger .

https://gist.github.com/Knighth/fb3b7992954c49685b78650b4b3219cd

**Comment by george-jones** [comment]
Thanks for the suggestions.  I will take a closer look and try to implement the fix when I'm back from vacation in about a week.

**Comment by george-jones** [comment]
@InsaneBuildEnvironment  - I've made the changes from Knighth's gist and updated on steam.  Please let me know if the crashes are still happening for you.
